### PR TITLE
Ensure CAS operations are atomic

### PR DESCRIPTION
**Pull request by kuujo**
This branch is the beginning of work to make CAS operations atomic. This PR currently only implements atomic CAS for `ZKAsyncMap`'s `putIfAbsent` method, but the pattern should be very similar for other implementations.

In order to achieve atomicity, this implementation simply uses optimistic locking. The implementation of the algorithm is intentionally dirty but easy to understand. It will undoubtedly need to be cleaned up and abstracted a bit.

This is sort of a naive implementation, though, as optimistic locking could cause a process to block if there are enough concurrent writes to the key. Currently, the implementation just uses exponential backoff for retries and fails after the 5th try by default. But ideally, the implementation could fall back on a fine grained locking mechanism in the event that optimistic locking proves fruitless.

### CODE REVIEW

**Comment by stream1984** [comment]
Hi Jordan
Does all the methods need CAS operations is that rely on last value as compare ?
so method `put` doesn't need CAS, am i right?

**Comment by kuujo** [comment]
That's correct. Setting a value without checking it is already atomic because of ZooKeeper's guarantees. It's only when a condition needs to be checked before setting a value that optimistic locking is required. Optimistic locking ensures that the value hasn't changed between the time ZooKeeper responds with the current value to check and the time ZooKeeper receives the updated value.

**Comment by stream1984** [comment]
I have merged your pull request to master, and refactor method `putIfAbsent` , `replace`, `replaceIfPresent`, abstract a method of `compareAndSet` to `ZKMap`.
may i have your review ? thanks :)
https://github.com/stream1984/vertx-zookeeper/commit/4c9862add467f4d7c5ae90c0f783475bf04c41b6

**Comment by kuujo** [comment]
Awesome! This is exciting.

We can get this thing in to the `vert-x3` organization in no time...

I will poke around a bit more later today again. I think optimistic locking is a decent solution. There is some risk of timeouts in cases where two processes are contending for the same resource under high load, but ZooKeeper is not designed for high throughput writes, so that case may be theoretical for most systems.

We might also want to add an option for configuring the retry strategy and number of retries. I'll add some more issues for anything I see.

**Pull request merged**
